"""Reference values for `test_examples.py`.

Regenerate the whole table with

    uv run python tests/test_examples.py

but do so only if the change is *intended*: these values encode the (verified)
agreement with the original Matlab codes.

Provenance:

- `quarter_five_spot` was generated by `matlab_codes/listing9.m`: `S(1:600:end)`.
- The others were generated by MiniRes itself
  (`quarter_five_spot`'s `scheduled` at an early commit; the rest when they were written).
- `buildup` was re-generated when it was re-posed in metric units
  (ref `minires.ResSim.cdarcy`), so its values are in bar, `perm_est` in mD.
- `egg` is likewise in metric units (bar, m³/day). Its `rms_cut`, `rel_oil` and
  `recovery` measure the agreement with the *external* 3D reference (ECLIPSE 100)
  that the example asserts, so they record a validation, not just a regression.
- `buckley_leverett` is the exception to all of the above: it does not rest on
  agreement with anything of ours -- the example itself asserts its agreement
  with the *analytic* solution. Its `welge` and `bt` values therefore double as
  a record that the analytics are being *derived*, not merely reproduced.
"""

references = {
    "aquifer": dict(
        sat_inf = [0.945548, 0.991321, 0.941139, 0.972314, 0.909883, 0.8896, 0.909157, 0.869686],
        sat_fin = [0.774933, 0.948951, 0.738429, 0.864293, 0.595904, 1.9471e-07, 0.0635516, 4.29379e-09],
        q_inf = [0.947324, 0.58754, 0.617168, 0.691189, 0.736087, 0.767154, 0.790294, 0.808267],
        q_fin = [0.947324, 0.226499, 0.0738105, 0.0306902, 0.0132822, 0.00579466, 0.00253473, 0.00110997],
        p_aq = [1, 0.306177, 0.119499, 0.0512797, 0.0223448, 0.00977065, 0.00427798, 0.00187411],
    ),
    "buckley_leverett": dict(
        explicit = [0.990913, 0.890405, 0.822983, 0.765383, 0.706094, 0, 0, 0],
        implicit = [0.990162, 0.883361, 0.811672, 0.747063, 0.65349, 0, 0, 0],
        case_B = [0.777458, 0.628782, 0.568634, 0.527593, 0.496772, 0.468914, 0.430758, 0.2],
        welge = [0.707107, 1.20711, 0.444949, 2.87457],
        water_cut = [0.0856744, 0.869728, 0.892704, 0.908574, 0.919621, 0.929471, 0.937468, 0.944081],
        bt = [0.82, 0.828427],
        L1 = [0.0268856, 0.0150174, 0.00684973, 0.00493806, 0.00233683],
    ),
    "buildup": dict(
        p_cell = [250, 232.86, 230.873, 246.473, 246.956, 246.996, 246.999, 247],
        p_far = [250, 249.567, 248.077, 246.99, 246.97, 246.984, 246.991, 246.995],
        p_mean = [250, 249, 247.5, 247, 247, 247, 247, 247],
        p_final = [247.009, 247.008, 247.006, 247.002, 246.998, 246.994, 246.992, 246.991],
        perm_est = [96.2918],
    ),
    "egg": dict(
        water_cut = [0, 0.400526, 0.904154, 0.916484, 0.94295, 0.953772, 0.9637, 0.976543],
        oil_rate = [133.1, 55.268, 12.9557, 25.8101, 17.3721, 3.80883, 2.99119, 2.49621],
        S_final = [0.1, 0.670822, 0.634604, 0.558449, 0.632944, 0.1, 0.578512, 0.1],
        bhp_inj = [403.019, 400.144, 402.129, 401.249, 399.903, 402.745, 402.217, 402.967],
        rms_cut = [0.00901207, 0.00995861, 0.0121032, 0.0108285],
        rel_oil = [0.0416654, 0.0559736, 0.0423121, 0.0362626],
        recovery = [0.571558, 0.590275],
    ),
    "history_match_gradient": dict(
        misfit = [0.0199474, 0.00508865, 0.00263975, 0.00119656, 0.000910828],
        gradient = [-6.55375e-17, 3.86969e-05, -1.95242e-05, -0.000222445, -0.000107272, 0.000161098, -7.66342e-05, 2.25565e-18],
        directional = [0.00617148, 0.00617148],
        corr = [0.188483],
        logK_final = [2.52974e-05, -0.13025, 0.0568243, 0.19166, 0.142903, -0.130376, 0.150458, -4.29551e-06],
    ),
    "inactive_cells": dict(
        sat_final = [0.374963, 0.960948, 0.684959, 0.880154, 0.635068, 0.556071, 0.758672, 0.580979],
        p_final = [1.70973e-14, -0.14133, -0.784923, -0.900964, -1.53616, -2.92508, -2.52524, -2.20174],
        water_cut = [0, 0, 0, 0.266929, 0.621439, 0.729267, 0.805573, 0.854635],
    ),
    "logo": dict(
        smiley = [1.30127e-32, 0.931946, 0.698974, 1.19755e-06, 0.210369, 0.295984, 0.0320383, 1.77064e-05],
    ),
    "pressure_diffusion": dict(
        dp_early = [0.314632, 0.00132661, 0.01226, -0.000672055, 0.000821872, -0.0108189, -0.00101512, -0.314632],
        dp_late = [0.559039, 0.0422538, 0.132284, -0.0225223, 0.0273494, -0.12519, -0.0354479, -0.559039],
        elliptic = [0.561286, 0.0429973, 0.13397, -0.022919, 0.0278314, -0.126825, -0.0360858, -0.561286],
        p_inj = [1, 1.43087, 1.50322, 1.52776, 1.54501, 1.5518, 1.55667, 1.55904],
    ),
    "quarter_five_spot": dict(
        # The explicit row agrees with the Matlab output to its 5 decimals (.99965,
        # .91968, .77584, .90268, .81068, .67467, .66065), and so did the implicit
        # one (.99963, .91573, .75736, .89799, .79862, .62061, .62483) until the
        # Corey curves were clipped to the unit interval (ref `Fluid.RelPerm`):
        # the Newton iterates pass outside it, where Matlab's polynomial and the
        # clipped curves differ, and the iteration stops at an update norm of 1e-3,
        # so the implicit row now agrees with Matlab's to 3-4 decimals only --
        # which is all its own tolerance ever guaranteed.
        explicit = [0.999653, 0.919677, 0.775843, 0.902681, 0.810679, 0.674671, 0.660654],
        implicit = [0.999628, 0.915592, 0.756757, 0.897823, 0.798072, 0.620755, 0.625079],
        # The scheduled variant was `rate_scheduling.py` (an example of its own until 2026-09).
        scheduled = [0.99949, 0.881942, 0.826531, 0.878561, 0.776629, 0.710515, 0.11659],
    ),
    "random_fields": dict(
        gamma_emp = [0.00187567, 0.141198, 0.419308, 0.691541, 0.886167, 0.962249, 0.987086, 0.992117],
        field_0 = [1.95012, -2.4859, 0.499996, 0.289721, -0.589673, -0.0563989, -0.394142, -0.404817],
        field_1 = [0.722625, 1.20659, 0.292731, -0.0452101, 0.6978, -0.872541, 1.25562, -0.155562],
        field_2 = [0.334297, 0.373484, 0.503139, 0.0314317, -0.106452, -0.695918, 0.0604238, -0.608257],
    ),
    "voidage_replacement": dict(
        sat_full = [0.999515, 0.934951, 0.976032, 0.899993, 0.929288, 0.874472, 0.856937, 0.825724],
        sat_half = [0.998472, 0.847911, 0.933851, 0.797146, 0.840301, 0.768707, 0.732017, 0.706502],
        prd_full = [0, 0, 0, 0.591944, 0.713273, 0.768264, 0.80234, 0.825724],
        prd_half = [0, 0, 0, 0, 0.530559, 0.629839, 0.679435, 0.706502],
        p_half = [15, 13.6, 12.15, 10.75, 9.3, 7.9, 6.45, 5],
    ),
    "water_cut_gradient": dict(
        water_cut = [0, 0, 0, 0.361664, 0.598089, 0.772906, 0.826112, 0.894585],
        gradient = [-0.0660733, -0.000875448, -0.00234812, -0.00423598, -0.00323221, 0.00618496, -0.00340247, 0.0323537],
        gradient_bhp = [0, 0, -0.300791, 0.033259, 0, 0, 0.0564881, 0],
        directional = [0.164432, 0.164432, -0.164767, -0.164767],
    ),
    "well_control": dict(
        rate_of_bhp_ctrl = [0.622077, 0.341664, 0.21485, 0.135109, 0.0831082, 0.0522631, 0.032866, 0.0202164],
        bhp_of_rate_ctrl = [0.79906, 0.667281, 0.562276, 0.457276, 0.347276, 0.242276, 0.137276, 0.0272763],
        p_last_bhp_ctrl = [0.519567, 0.518555, 0.518959, 0.516987, 0.517654, 0.518229, 0.518302, 0.518945],
        rate_of_limited = [0.25, 0.25, 0.25, 0.205883, 0.126636, 0.079636, 0.0500796, 0.0308049],
        bhp_of_limited = [0.79906, 0.667281, 0.562276, 0.5, 0.5, 0.5, 0.5, 0.5],
    ),
    "well_path": dict(
        alloc_static = [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625],
        alloc_bhp = [0.0128816, 0.0131298, 0.0138058, 0.0148435, 0.0161053, 0.0173625, 0.0183188, 0.0187026],
        sat_point = [0.999653, 0.919677, 0.775843, 0.902681, 0.810679, 0.674671, 0.660654],
        sat_path = [0.980677, 0.903463, 0.85529, 0.785376, 0.749434, 0.752974, 0],
    ),
}
